apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: mendhak/http-https-echo:33
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret
        volumeMounts:
        - name: app-config-volume
          mountPath: /etc/app-config
          readOnly: true
      volumes:
      - name: app-config-volume
        configMap:
          name: app-config
      serviceAccountName: app-service-account