apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: nginx:1.28.2
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: hello-config
          - secretRef:
              name: hello-secret
        volumeMounts:
          - name: hello-config-volume
            mountPath: /etc/hello-config
            readOnly: true
      volumes:
        - name: hello-config-volume
          configMap:
              name: hello-config